/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./src/**/*.{html,ts}",
    // "./node_modules/flowbite/**/*.js", // add this line
  ],
  theme: {
    extend: {
      colors: {
        "jacksons-purple": {
          50: "#eaf2ff",
          100: "#d9e7ff",
          200: "#bad1ff",
          300: "#90b1ff",
          400: "#6585ff",
          500: "#4159ff",
          600: "#2029ff",
          700: "#151aed",
          800: "#151cbe",
          900: "#1a2293",
          950: "#101356",
        },
        'cod-gray': {
    '50': '#f5f5f6',
    '100': '#e5e6e8',
    '200': '#cdced4',
    '300': '#aaacb6',
    '400': '#7f8191',
    '500': '#646676',
    '600': '#565764',
    '700': '#4a4b54',
    '800': '#414149',
    '900': '#393940',
    '950': '#070708',
},

      },
    },
    fontFamily: {
      body: [
        "Inter",
        "ui-sans-serif",
        "system-ui",
        "-apple-system",
        "system-ui",
        "Segoe UI",
        "Roboto",
        "Helvetica Neue",
        "Arial",
        "Noto Sans",
        "sans-serif",
        "Apple Color Emoji",
        "Segoe UI Emoji",
        "Segoe UI Symbol",
        "Noto Color Emoji",
      ],
      sans: [
        "Inter",
        "ui-sans-serif",
        "system-ui",
        "-apple-system",
        "system-ui",
        "Segoe UI",
        "Roboto",
        "Helvetica Neue",
        "Arial",
        "Noto Sans",
        "sans-serif",
        "Apple Color Emoji",
        "Segoe UI Emoji",
        "Segoe UI Symbol",
        "Noto Color Emoji",
      ],
    },
  },
  safelist: ["bg-red-500", "text-3xl", "lg:text-4xl"],
  // plugins: [require("flowbite/plugin")({ charts: true })],
};
